export const portfolioData = {
    publications: [
      {
        authors: ["Zeng, Danqi", "Yahan Yang", "Yang Tang", "Lanqin Zhao", "Xun Wang", "Dongyuan Yun", "Wenben Chen et al."],
        year: 2025,
        title: "Shaping school for childhood myopia: the association between floor area ratio of school environment and myopia in China.",
        journal: "British Journal of Ophthalmology 109, no. 1 (2025): 146-151.",
        type: "Journal",
      },
      {
        authors: ["Tang, Yang", "Guixiang Zhang", "Jung Kuan Liu", "Rongjun Qin"],
        year: 2025,
        title: "Weakly supervised land-cover classification of high-resolution images with low-resolution labels through optimized label refinement.",
        journal: "International Journal of Remote Sensing (2025): 1-25.",
        type: "Journal",
      },
      {
        authors: ["Shum, C. K.", "Shengdao Wang", "Yu Zhang", "Yixin Xiao", "Yang Tang", "Metehan Uz", "Kazim Atman et al."],
        year: 2025,
        title: "Geodesy for Climate Actions.",
        journal: "In IAG Scientific Assembly 2025. 2025.",
        type: "Conference",
      },
      {
        authors: ["Gui, Shengxi", "Shuang Song", "Rongjun Qin", "Yang Tang"],
        year: 2024,
        title: "Remote sensing object detection in the deep learning era—a review.",
        journal: "Remote Sensing 16, no. 2 (2024): 327.",
        type: "Journal",
        isHighlyCited: true,
        isEditorsChoice: true,
      },
      {
        authors: ["Albanwan, Hessah", "Rongjun Qin", "Yang Tang"],
        year: 2024,
        title: "Image Fusion in Remote Sensing: An Overview and Meta-Analysis.",
        journal: "Photogrammetric Engineering & Remote Sensing 90, no. 12 (2024): 755-775.",
        type: "Journal",
      },
      {
        authors: ["Tang, Yang", "Shuang Song", "Shengxi Gui", "Weilun Chao", "Chinmin Cheng", "Rongjun Qin"],
        year: 2023,
        title: "Active and low-cost hyperspectral imaging for the spectral analysis of a low-light environment.",
        journal: "Sensors 23, no. 3 (2023): 1437.",
        type: "Journal",
        isHighlyCited: true,
        isEditorsChoice: true,
      },
      {
        authors: ["Qin, Rongjun", "Guixiang Zhang", "Yang Tang"],
        year: 2023,
        title: "On the transferability of learning models for semantic segmentation for remote sensing data.",
        journal: "arXiv preprint arXiv:2310.10490 (2023).",
        type: "Journal",
      },
      {
        authors: ["Zuo, Ying", "C. K. Shum", "Soumitri Das", "Yuanyuan Jia", "Orhan Akyilmaz", "Yu Zhang", "Yang Tang et al."],
        year: 2023,
        title: "Satellite-based tools enabling India forest sustainability.",
        journal: "In XXVIII General Assembly of the International Union of Geodesy and Geophysics (IUGG). GFZ German Research Centre for Geosciences, 2023.",
        type: "Conference",
      },
      {
        authors: ["Huang, Debao", "Yang Tang", "Rongjun Qin"],
        year: 2022,
        title: "An evaluation of planetscope images for 3d reconstruction and change detection–experimental validations with case studies.",
        journal: "GIScience & Remote Sensing 59, no. 1 (2022): 744-761.",
        type: "Journal",
      },
      {
        authors: ["Gui, Shengxi", "Rongjun Qin", "Yang Tang"],
        year: 2022,
        title: "SAT2LOD2: a software for automated LOD-2 building reconstruction from satellite-derived orthophoto and digital surface model.",
        journal: "The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences 43 (2022): 379-386.",
        type: "Conference",
      },
      {
        authors: ["Jia, Yuanyuan", "C. K. Shum", "Ying Zuo", "Yang Tang"],
        year: 2022,
        title: "Satellite Remote Sensing-Based Environmental Monitoring of Inland Water and Natural Hazards Towards Forest Sustainability over India.",
        journal: "In AGU Fall Meeting Abstracts, vol. 2022, pp. G31A-04. 2022.",
        type: "Conference",
      },
      {
        authors: ["Tang, Yang", "Jiongchao Yan", "Yueqi Wu", "Jie Hong", "Lei Xu", "Zhangrui Lin"],
        year: 2021,
        title: "Design of remote sensing image data analysis and processing platform based on environmental monitoring.",
        journal: "In Journal of Physics: Conference Series, vol. 2136, no. 1, p. 012056. IOP Publishing, 2021.",
        type: "Conference",
      },
      {
        authors: ["Lai, Xin", "Yang Tang", "Lei Li", "PakWai Chan", "Qingfeng Zeng"],
        year: 2019,
        title: "Study on microclimate observation network for urban unit: A case study in a campus of Shenzhen, China.",
        journal: "Physics and Chemistry of the Earth, Parts A/B/C 110 (2019): 117-124.",
        type: "Journal",
      },
      {
        authors: ["曾庆锋", "高瑞泉", "温精敏", "李磊", "许磊", "汤洋", "赖鑫"],
        year: 2019,
        title: "基于物联网的城市单元体微气候环境观测管理模式.",
        journal: "收藏 3 (2019).",
        type: "Journal",
      },
      {
        authors: ["Tang, Yang", "Kawahara Yoshihiro", "Asami Tohru", "Bollegala Danushka"],
        year: 2013,
        title: "BS-1-12 Analyzing Patterns from Twitter Happiness referring Stock Market and American Unemployment Rate Announcement.",
        journal: "電子情報通信学会総合大会講演論文集 2013, no. 2 (2013): S-23.",
        type: "Conference",
      },
    ],
    awards: [
        { year: "2024, 2025", award: "Editor’s Choice Paper", institution: "For papers in 'Sensors' and 'Remote Sensing'." },
        { year: "2023, 2024", award: "Top 1% Highly Cited Paper", institution: "Web of Science (Fields: Analytical Chemistry, Geosciences)." },
        { year: "2023", award: "Second Place Poster Award (2/45)", institution: "Translational Data Analytics Institute, The Ohio State University." },
        { year: "2013", award: "Excellent Student & Excellent Graduate", institution: "Denmark Technical University." },
        { year: "2012–2013", award: "JASSO Short-Term Scholarship", institution: "Tokyo University, Japan." },
        { year: "2011–2013", award: "DTU Scholarship", institution: "Technical University of Denmark." },
        { year: "2009–2011", award: "Academic Performance Scholarship", institution: "Wroclaw University of Technology, Poland." },
    ],
    experience: [
        { role: "Ph.D. in Civil, Environmental and Geodetic Engineering", company: "The Ohio State University, Columbus, OH", duration: "2021 – Present" },
        { role: "Data Scientist", company: "Shenzhen Bixuange Technology Co., Ltd., Shenzhen, China", duration: "Jan 2014 – Aug 2020" },
        { role: "Intern", company: "Map Motion Co., Ltd., Tokyo, Japan", duration: "Jan 2013 – Feb 2013" },
        { role: "Teaching Assistant, Artificial Intelligence", company: "Wroclaw University of Technology, Wroclaw, Poland", duration: "Oct 2010 – Jul 2011" },
        { role: "Artificial Intelligence Programmer", company: "Vratis, Wroclaw, Poland", duration: "Jun 2010 – Oct 2010" },
    ],
    skills: {
        "Programming Languages": ["Python", "R", "MATLAB", "C++"],
        "Data Science & ML Libraries": ["PyTorch", "TensorFlow", "Scikit-learn", "Pandas", "GeoPandas", "GDAL"],
        "Geospatial Software": ["QGIS", "ENVI", "ArcGIS"],
        "Tools & Platforms": ["Git", "Docker", "KNIME", "Linux"],
    },
    professionalActivities: {
        reviewing: [
            "ISPRS Journal of Photogrammetry and Remote Sensing",
            "IEEE International Geoscience and Remote Sensing Symposium (IGARSS)",
            "IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing",
            "Photogrammetric Engineering and Remote Sensing",
            "Transactions on Emerging Telecommunications Technologies",
            "Transactions on Consumer Electronics",
            "Journal of Biophotonics",
            "IEEE Journal of Biomedical and Health Informatics",
            "Additive Manufacturing",
            "Geocarto International"
        ],
        memberships: [
            "IEEE Geoscience and Remote Sensing Society (GRSS)",
            "American Society for Photogrammetry and Remote Sensing (ASPRS)",
            "International Society for Photogrammetry and Remote Sensing (ISPRS)",
            "American Geophysical Union (AGU)",
            "European Geosciences Union (EGU)",
            "Institute of Electrical and Electronics Engineers (IEEE)"
        ]
    }
};
